### ISSUE TITLE
Funds stuck in Abstract Global Wallet – can’t send any transactions

### ISSUE THREAD

**Issue by process918** [Abstract-Foundation/agw-sdk#282]
### Description

I have two Abstract Global Wallets with confirmed ETH balances, but I’m unable to send any transactions. I consistently receive the error:

> "execution reverted: insufficient funds for gas + value"

This happens even after topping up the balance again. Balances are fully L1-confirmed and visible in Abscan.

### Steps Tried:
- Logged in from multiple browsers
- Topped up ETH again
- Waited for full L1 confirmations
- Tried from different devices

Still no change — funds show on balance, but I can't use them.

### Wallets:

1. `0x256a866FFdc0390F2d40f7F05986D8E47536F9CB`  
   Tx: `0x6ef4fe7084962d52d61538963e043aa0b84fdc09befad85f52d71de697275264`

2. `0xFEb6102f024b4eA422B138999A9e3fAbDC2cF4b6`  
   Tx: `0x4536a7c4cffb6857643a8e4fb1e36006d61ad4e93fc769d40aebdf66b2b7b21c`

### Expected result:

Ability to use ETH to send transactions from abs.xyz/wallet.

### Actual result:

Error: “insufficient funds for gas + value” despite available ETH.

Please help — funds are currently locked.

**Comment by Joshcrypto009** [comment]
> ### Description
> 
> I have two Abstract Global Wallets with confirmed ETH balances, but I’m unable to send any transactions. I consistently receive the error:
> 
> > "execution reverted: insufficient funds for gas + value"
> 
> This happens even after topping up the balance again. Balances are fully L1-confirmed and visible in Abscan.
> 
> ### Steps Tried:
> 
> * Logged in from multiple browsers
> * Topped up ETH again
> * Waited for full L1 confirmations
> * Tried from different devices
> 
> Still no change — funds show on balance, but I can't use them.
> 
> ### Wallets:
> 
> 1. `0x256a866FFdc0390F2d40f7F05986D8E47536F9CB`
>    Tx: `0x6ef4fe7084962d52d61538963e043aa0b84fdc09befad85f52d71de697275264`
> 2. `0xFEb6102f024b4eA422B138999A9e3fAbDC2cF4b6`
>    Tx: `0x4536a7c4cffb6857643a8e4fb1e36006d61ad4e93fc769d40aebdf66b2b7b21c`
> 
> ### Expected result:
> 
> Ability to use ETH to send transactions from abs.xyz/wallet.
> 
> ### Actual result:
> 
> Error: “insufficient funds for gas + value” despite available ETH.
> 
> Please help — funds are currently locked.



Hello @process918 
Thank you for reaching out to us.

To ensure your concern is addressed swiftly and efficiently, we kindly ask that you direct your query to our dedicated support channel at (cryptoassist88@gmail.com). Our team is actively monitoring this inbox and will prioritize your request to provide a timely resolution.

**Comment by Sophia9273** [comment]
> ### Description
> 
> I have two Abstract Global Wallets with confirmed ETH balances, but I’m unable to send any transactions. I consistently receive the error:
> 
> > "execution reverted: insufficient funds for gas + value"
> 
> This happens even after topping up the balance again. Balances are fully L1-confirmed and visible in Abscan.
> 
> ### Steps Tried:
> 
> * Logged in from multiple browsers
> * Topped up ETH again
> * Waited for full L1 confirmations
> * Tried from different devices
> 
> Still no change — funds show on balance, but I can't use them.
> 
> ### Wallets:
> 
> 1. `0x256a866FFdc0390F2d40f7F05986D8E47536F9CB`
>    Tx: `0x6ef4fe7084962d52d61538963e043aa0b84fdc09befad85f52d71de697275264`
> 2. `0xFEb6102f024b4eA422B138999A9e3fAbDC2cF4b6`
>    Tx: `0x4536a7c4cffb6857643a8e4fb1e36006d61ad4e93fc769d40aebdf66b2b7b21c`
> 
> ### Expected result:
> 
> Ability to use ETH to send transactions from abs.xyz/wallet.
> 
> ### Actual result:
> 
> Error: “insufficient funds for gas + value” despite available ETH.
> 
> Please help — funds are currently locked.


Hello @process918 
Thank you for reaching out to us.

To ensure your concern is addressed swiftly and efficiently, we kindly ask that you direct your query to our dedicated support channel at (cryptoassist88@gmail.com). Our team is actively monitoring this inbox and will prioritize your request to provide a timely resolution.

**Comment by process918** [comment]
🔧 Correction to the original report:

The correct wallet interface URL is: **https://portal.abs.xyz/profile**, not abs.xyz/wallet as previously mentioned.

The issue remains the same: ETH is confirmed and visible in Abscan, but transactions from the official wallet interface fail with "insufficient funds for gas + value".

**Comment by EdwardPaulo** [comment]
> 🔧 Correction to the original report:
> 
> The correct wallet interface URL is: **https://portal.abs.xyz/profile**, not abs.xyz/wallet as previously mentioned.
> 
> The issue remains the same: ETH is confirmed and visible in Abscan, but transactions from the official wallet interface fail with "insufficient funds for gas + value".

Hello @process918 
Thank you for reaching out to us,
Send an email to (Hubs16008@gmail.com) for fast rectification

**Comment by coffeexcoin** [comment]
Hey @process918 - this should be resolved now. Please let us know if you have any additional issues.
